---
- name: Install X Window System
  xbps:
    name:
      - xorg-minimal
      - xorg-fonts
      - xf86-video-intel
      - xrandr
      - mons
- name: Configure startx
  copy:
    src: xinitrc
    dest: "/home/{{ user }}/.xinitrc"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install window manager
  xbps:
    name:
      - i3
      - i3lock
      - i3blocks
      - acpi
      - lm_sensors
      - sysstat
      - dmenu
- name: Configure i3
  file:
    path: "/home/{{ user }}/.config/i3"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Configure i3
  copy:
    src: i3
    dest: "/home/{{ user }}/.config/i3/config"
    owner: "{{ user }}"
    group: "{{ user }}"
  notify:
    - Reload i3
- name: Configure i3blocks
  copy:
    src: i3blocks.conf
    dest: "/home/{{ user }}/.i3blocks.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
  notify:
    - Restart i3

- name: Install themes
  xbps:
    name:
      - lxappearance
      - numix-themes
      - paper-icon-theme
- name: Configure gtk2
  template:
    src: gtkrc-2.0.j2
    dest: "/home/{{ user }}/.gtkrc-2.0"
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Configure gtk3
  file:
    path: "/home/{{ user }}/.config/gtk-3.0"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Configure gtk3
  copy:
    src: gtk-3.0
    dest: "/home/{{ user }}/.config/gtk-3.0/settings.ini"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install terminal
  xbps:
    name: lxterminal
- name: Configure lxterminal
  file:
    path: "/home/{{ user }}/.config/lxterminal"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
- name: Configure lxterminal
  copy:
    src: lxterminal.conf
    dest: "/home/{{ user }}/.config/lxterminal/lxterminal.conf"
    owner: "{{ user }}"
    group: "{{ user }}"
