---
- name: Install network daemon
  xbps:
    name:
      - wicd
      - wicd-gtk
      - dbus
- name: Disable dhcpcd
  runit:
    name: dhcpcd
    enabled: no
- name: Disable wpa_supplicant
  runit:
    name: wpa_supplicant
    enabled: no
- name: Enable dbus
  runit:
    name: dbus
    enabled: yes
    state: started
- name: Enable wicd
  runit:
    name: wicd
    enabled: yes
    state: started
- name: Add user to users group
  user:
    name: "{{ user }}"
    groups: users
    append: yes

- name: Install network tools
  xbps:
    name:
      - curl
      - mtr
      - wget
