if $USER ==# "root"
  set backup
else
  set nobackup
endif
set hidden              " Hide buffers when they are abandoned
set shiftwidth=4        " Number of spaces to use for (auto)indent
set softtabstop=4       " Number of spaces that a <Tab> counts for
set expandtab           " Insert spaces instead of <Tab>s
set hlsearch            " Highlight all search matches

let g:solarized_termcolors=256
set background=dark
colorscheme solarized
